spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: devuser
    password: pirate
management:
  endpoints:
    web:
      exposure:
        include: health, info
